version: '3'
services:
  webserver:
    build: node
    # Must change
    image: app-server:0.1
    tty: true
    volumes:
      - ./node/app:/app
    ports:
      - "8000:8000"

# build
# $ docker-compose build
#
# up
# $ docker-compose up -d
#
# exec terminal
# $ docker exec -it [CONTAINER_NAME] /bin/sh
